// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/block": {
            "get": {
                "description": "Метод получение блока контента по id и/или названию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получение блока контента по id и/или названию.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id блока",
                        "name": "block_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "название блока",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/block/list": {
            "get": {
                "description": "Метод получения списка id и названий всех блоков.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получение списка id и названий всех блоков.",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/block/{block_id}": {
            "get": {
                "description": "Метод получения элемента контента из блока по id, названию или типу контента.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получение элементов контента из блока по id, названию или типу контента.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id блока",
                        "name": "block_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id контента",
                        "name": "content_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "название элемента контента",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "тип контента (1 - баннер, 2 - истории, 3 - тесты)",
                        "name": "content_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/block/{block_id}/list": {
            "get": {
                "description": "Метод получения списка id и названий элементов контента для блока.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получение списка id и названий элементов контента для блока.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id блока",
                        "name": "block_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Health check.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check.",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/scenario/block/{user_id}/list/{block_id}": {
            "get": {
                "description": "Метод получения списка id и названий элементов контента для блока.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Получение списка id и названий элементов контента для блока.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id блока",
                        "name": "block_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/scenario/block/{user_id}/{block_id}": {
            "get": {
                "description": "Метод получения элемента контента из блока по id, названию или типу контента.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Получение элемента контента из блока по id, названию или типу контента.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id блока",
                        "name": "block_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id контента",
                        "name": "content_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "название элемента контента",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "тип контента (1 - баннер, 2 - истории, 3 - тесты)",
                        "name": "content_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/scenario/blocks/{user_id}": {
            "get": {
                "description": "Метод получение блока контента определенного типа по id и/или названию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Получение блока контента по id и/или названию для пользователя.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id блока",
                        "name": "block_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "название блока",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/scenario/list/{user_id}": {
            "get": {
                "description": "Метод получения списка id и названий блоков, доступных пользователю по сценарию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Получение списка id и названий блоков, доступных пользователю по сценарию.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/scenario/{user_id}": {
            "get": {
                "description": "Метод получение всего контента, который доступен пользователю по его сценарию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Получение всего контента по сценарию пользователя.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/template": {
            "get": {
                "description": "Метод получения шаблона по id, названию или типу контента.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получение шаблона по id, названию или типу.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id шаблона",
                        "name": "template_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "название шаблона",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "тип шаблона (1 - баннер, 2 - истории, 3 - тесты)",
                        "name": "content_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/template/list": {
            "get": {
                "description": "Метод получения списка id, названий и типов всех шаблонов.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Получение списка id, названий и типов всех шаблонов.",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Content Service API",
	Description:      "Контент сервис - сервис хранения контента (баннеры, тесты, истории и т.д.) для дальнейшего отображения его на клиенте пользователя.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
